# Generated by Django 5.2 on 2025-04-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
