# Generated by Django 5.2 on 2025-04-07 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Rollno',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='student',
            name='subject1',
            field=models.CharField(default='Physics', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='subject2',
            field=models.CharField(default='Maths', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='subject3',
            field=models.CharField(default='Chemistry', max_length=30),
        ),
    ]
