# Generated by Django 5.2 on 2025-04-08 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_student_rollno_student_subject1_student_subject2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Tid', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('Tname', models.CharField(default='physics', max_length=30)),
            ],
        ),
    ]
