# Generated by Django 5.2 on 2025-04-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Name',
        ),
    ]
