# Generated by Django 5.2 on 2025-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Name',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Tname',
            field=models.CharField(default='Physics', max_length=30),
        ),
    ]
