# Generated by Django 5.2 on 2025-04-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_teacher_name_alter_teacher_tname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
